version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: diploma
    environment:
      - 'POSTGRES_DB=diploma'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_MAX_CONNECTIONS=200'
    ports:
      - "5432:5432"
    restart: unless-stopped

  diplomaAirline:
    image: DiplomaAirline:latest
    container_name: DiplomaAirline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - 'MAX_HEAP_SIZE=4G'
      - 'HEAP_NEWSIZE=2G'
    ports:
      - "9042:9042"


  greenplum-db:
    image: andruche/greenplum:7
    container_name: greenplum-container
    environment:
      - 'GPDB_DATABASE=diploma'
    ports:
      - "5432:5432"
